//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FxPu.Utils.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FxPu.Utils.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{source}} must be between {0} and {1}..
        /// </summary>
        internal static string ValidateIsBetween {
            get {
                return ResourceManager.GetString("ValidateIsBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{source]}} must be between {0} and {1} or empty..
        /// </summary>
        internal static string ValidateIsBetweenOrIsNull {
            get {
                return ResourceManager.GetString("ValidateIsBetweenOrIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{source}} must not be empty..
        /// </summary>
        internal static string ValidateIsEmpty {
            get {
                return ResourceManager.GetString("ValidateIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{source}} must not be equal to &quot;{0}&quot;..
        /// </summary>
        internal static string ValidateIsEqual {
            get {
                return ResourceManager.GetString("ValidateIsEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{source}}must be true..
        /// </summary>
        internal static string ValidateIsFalse {
            get {
                return ResourceManager.GetString("ValidateIsFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{source}} must be in &quot;{0}&quot;..
        /// </summary>
        internal static string ValidateIsIn {
            get {
                return ResourceManager.GetString("ValidateIsIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{source}} must not have more than {0} characters..
        /// </summary>
        internal static string ValidateIsInMaxLength {
            get {
                return ResourceManager.GetString("ValidateIsInMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{source}} must not contain one of the following characters &quot;{0}&quot;..
        /// </summary>
        internal static string ValidateIsNoInvalidChars {
            get {
                return ResourceManager.GetString("ValidateIsNoInvalidChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{source}} must be empty..
        /// </summary>
        internal static string ValidateIsNotEmpty {
            get {
                return ResourceManager.GetString("ValidateIsNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{source]}} must be equal to {0}..
        /// </summary>
        internal static string ValidateIsNotEqual {
            get {
                return ResourceManager.GetString("ValidateIsNotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{source}} must not be in &quot;{0}&quot;..
        /// </summary>
        internal static string ValidateIsNotIn {
            get {
                return ResourceManager.GetString("ValidateIsNotIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{source}} must be null..
        /// </summary>
        internal static string ValidateIsNotNull {
            get {
                return ResourceManager.GetString("ValidateIsNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{source}} must not be null..
        /// </summary>
        internal static string ValidateIsNull {
            get {
                return ResourceManager.GetString("ValidateIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{source}} must match regex pattern {0}..
        /// </summary>
        internal static string ValidateIsRegexMatch {
            get {
                return ResourceManager.GetString("ValidateIsRegexMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{source}} must match regex pattern {0} or be empty..
        /// </summary>
        internal static string ValidateIsRegexMatchOrIsNull {
            get {
                return ResourceManager.GetString("ValidateIsRegexMatchOrIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{source}} must be false..
        /// </summary>
        internal static string ValidateIsTrue {
            get {
                return ResourceManager.GetString("ValidateIsTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string ValidateValue {
            get {
                return ResourceManager.GetString("ValidateValue", resourceCulture);
            }
        }
    }
}
